upload_picture/upload_app/urls.py
from django.urls import path
from .import  views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'upload_app'
urlpatterns = [
    path('', views.mainPage, name = 'MainPage'),
    path('pic_upload/', views.pic_upload, name='Pic_upload'),
    path('pic_show/', views.pic_show, name='Pic_show'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload_picture/upload_picture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload_app.urls')),
]

upload_picture/upload_app/models.py
from django.db import models

# Create your models here.
class Picture(models.Model):
    picture = models.ImageField(upload_to='pictures/')

upload_picture/upload_app/forms.py
from django import forms
from .models import Picture

class pic_Form(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['picture']      

upload_picture/upload_app/views.py
from django.shortcuts import render, redirect
from .forms import pic_Form
from .models import Picture


def mainPage(request):
    return render(request, 'first/home.html')


def pic_upload(request):
    if request.method == 'POST':
        form = pic_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('upload_app:Pic_upload')
    else:
        form = pic_Form()
    pictures = Picture.objects.all()
    return render(request, 'first/pic_upload.html', {'form': form})

def pic_show(request):
    pictures = Picture.objects.all()
    return render(request, 'first/pic_show.html', {'pictures': pictures})

upload_picture/upload_app/templates/first/home.html
<!DOCTYPE html>
<html lang="en">
<heade>
	<meta charset="UTF-8">
	<title>HomePage</title>
</head>
<body>

<body style="background-color: 	#FF6103;">

	<a href = "{% url 'upload_app:Pic_upload' %}">Pic_upload</a>
	<a href = "{% url 'upload_app:Pic_show' %}">Pic_show</a>
</body>
</html>

upload_picture/upload_app/templates/first/pic_show.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
<a href = "{% url 'upload_app:MainPage' %}">back to MainPage</a>
</head>
<body>

<body style="background-color: 	#FF6103;">
 <li>
{% for picture in pictures %}
    <img src="picture">
  </li>
{% endfor %}

</html>

upload_picture/upload_app/templates/first/pic_upload.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Image Upload</title>
<a href = "{% url 'upload_app:MainPage' %}">back to MainPage</a>
</head>
<body>

<body style="background-color: 	#FF6103;">

    <h1>Image Upload</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>