pt/protype/first/urls.py
from django.urls import path, include
from .import  views

app_name = 'first'
urlpatterns = [
    path('', views.mainPage, name = 'MainPage'),
    path('login/', views.logIn, name = 'Login'),
    path('logout/', views.logOut, name = 'Logout'),
    path('register/', views.regist, name = 'Register'),
    path('pic_upload/', views.pic_upload, name='Pic_upload'),
    path('pic_show/', views.pic_show, name='Pic_show'),
]

pt/protype/protype/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls')),
]

pt/protype/first/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here

class teacherChart(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE)
    AuburnID = models.CharField(blank = True,max_length = 50)
    
    
    
    class Meta:
            verbose_name_plural = "TeacherChart"

class Picture(models.Model):
    picture = models.ImageField(upload_to='pictures/')

pt/protype/first/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Picture

class customizeRegistList(UserCreationForm):
    AuburnID = forms.CharField(required = False,max_length = 50)
    
    class Meat:
        model = User
        fields = ('AuburnID')
        
class pic_Form(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['title', 'picture']        

pt/protype/first/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import customizeRegistList
from .models import teacherChart
from .forms import pic_Form
from .models import Picture
# Create your views here.

def mainPage(request):
    return render(request, 'first/home.html')

def logIn(request):
    if request.method == 'POST':
       user = authenticate(request, username = request.POST['Username'], password = request.POST['Passwords'])
       if user is None:
           return render(request, 'first/login.html', {'error':'incorrect username or passwords'})
       else:
            login(request, user)
            return redirect('first:MainPage')
    else:
        return render(request, 'first/login.html')
    
def logOut(request):
    logout(request)
    return redirect('first:MainPage')

def regist(request):
    if request.method == 'POST':
        registList = customizeRegistList(request.POST)
        if registList.is_valid():
            registList.save()
            user = authenticate(username = registList.clean_data['username'], password = registList.clean_data['password1'])
            teacherChart(AuburnID = registList.clean_data['AuburnID']).save()
            login(request, user)
            return redirect('first:MainPage')
    else:
        registList = customizeRegistList()
    detail = {'registList' : registList}
    return render(request, 'first/register.html', detail)

def pic_upload(request):
    if request.method == 'POST':
        form = pic_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('first:Pic_upload')
    else:
        form = pic_Form()
    pictures = Picture.objects.all()
    return render(request, 'first/pic_upload.html', {'form': form})

def pic_show(request):
    pictures = Picture.objects.all()
    return render(request, 'first/pic_show.html', {'pictures': pictures})

pt/protype/first/templates/first/home.html
<!DOCTYPE html>
<html lang="en">
<heade>
	<meta charset="UTF-8">
	<title>HomePage</title>
</head>
<body>
	<h1>MainPage<h1>
	{% if user.is_authenticated %}
		<a href = "{% url 'first:Logout' %}">Logout</a> 
	{% else %}
		<a href = "{% url 'first:Login' %}">Login</a>
		<a href = "{% url 'first:Register' %}">Register</a>  
	{% endif %}
	
	<a href = "{% url 'first:Pic_upload' %}">Pic_upload</a>
	<a href = "{% url 'first:Pic_show' %}">Pic_show</a>
</body>
</html>

pt/protype/first/templates/first/login.html
<!DOCTYPE html>
<html lang="en">
<heade>
	<meta charset="UTF-8">
	<title>login</title>
</head>
<body>
	<h1> Login <h1>
	<a href = "{% url 'first:MainPage' %}">back to MainPage</a>
	<form action = "" method = "POST">
	{% csrf_token %}
	{{ error }}
	<input type = "text" name = "Username" placeholder = "Username">
	<input type = "password" name = "Passwords" placeholder = "Paasswords">
	<button type = "submit">Login</button>
</form>
</body>
</html>

pt/protype/first/templates/first/pic_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- CSS Styling -->
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="stylesheets/styles.css">
    <title>Question</title>
</head>
<body style="background-color: 	#FF6103;">
<body>
    <nav class="navbar nav navbar-dark navbar-expand-sm fixed-top">
        <div class="container">
            <button class="navbar-toggler my-auto" type="button" data-bs-toggle="collapse" data-bs-target="#Navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="./index.html"><img src="logo.png" height="40"></a>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="./index.html"><span class="fa fa-home fa-lg"></span> Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% for picture in pictures %}
    <img src="{{ picture.image.url }}">
{% endfor %}
    <div class="container mt-4">
        <!-- Question Number Card -->
        <div class="row row-content align-self-center">
            <div class="col-12 col-sm-8 offset-sm-2">
                <div class="card question-number-card d-flex align-items-center justify-content-center">
                    <div class="card-body">
                        <p class="text-center"><strong>Question #1</strong></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Question Body Card -->
        <div class="row row-content align-self-center">
            <div class="col-12 col-sm-8 offset-sm-2 mt-2">
                <div class="card question-body-card d-flex align-items-center justify-content-center">
                    <div class="card-body">

                    </div>
                </div>
            </div>
        </div>

        <!-- Question Choies Card -->
        <div class="row row-content align-self-center">
            <div class="col-12 col-sm-8 offset-sm-2 mt-2">
                <div class="card question-choices-card d-flex align-items-center justify-content-center w-100">
                    <div class="card-body col-12">
                        <form>
                            <div class="form-group text-center">
                                <button type="button" class="btn btn-block choice-button my-2 mx-auto" name="choice" data-bs-toggle="button" id="choice-1"><b>A) </b></button>
                                <button type="button" class="btn btn-block choice-button my-1 mx-auto" name="choice" data-bs-toggle="button" id="choice-2"><b>B) </b></button>
                                <button type="button" class="btn btn-block choice-button my-2 mx-auto" name="choice" data-bs-toggle="button" id="choice-3"><b>C) </b></button>
                                <button type="button" class="btn btn-block choice-button my-2 mx-auto" name="choice" data-bs-toggle="button" id="choice-4"><b>D) </b></button>
                            </div>

                            <div class="form-group text-center mt-3">
                                <button type="submit" class="btn btn-primary btn-block w-50">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <!-- jQuery first, then Popper.js, then Bootstrap JS. -->
    <script src="node_modules/jquery/dist/jquery.slim.min.js"></script>
    <script src="node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

</body>

</html>

pt/protype/first/templates/first/pic_upload.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Image Upload</title>
</head>
<body>
    <h1>Image Upload</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>

pt/protype/first/templates/first/register.html
<!DOCTYPE html>
<html lang="en">
<heade>
	<meta charset="UTF-8">
	<title>Register</title>
</head>
<body>
	<h1> Register <h1>
	<a href = "{% url 'first:MainPage' %}">back to MainPage</a>
	
	{% if registList.errors %}
		<p>{{ registList.errors }}</p>
	{% endif %}

	<form action = "" method = "POST">
		{% csrf_token %}
		{{ registList.as_p }}
		<button type = "submit">Register</button>
	</form>
</body>
</html>